# This workflow is to create a release with prebuilt create_llvm_prof binary.
name: Create Release Build

on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

  # Manual trigger using the Actions page.
  workflow_dispatch:

jobs:
  build_release:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: 'recursive'
        ref: '${{github.ref}}'

    - name: Install Dependencies
      run: sudo apt-get -y install libunwind-dev libgflags-dev libssl-dev libelf-dev protobuf-compiler libzstd-dev

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=Release -DENABLE_TOOL=LLVM -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++ -S ${{github.workspace}}

    - name: Build
      # Build your program with the given configuration
      run: make -C ${{github.workspace}}/build -j8

    - name: Run Tests
      run: make -C ${{github.workspace}}/build test

    - name: Create Zip Package
      run: |
        zip --junk-paths create_llvm_prof-x86_64-${{github.ref_name}}.zip ${{github.workspace}}/build/create_llvm_prof

    - uses: actions/upload-artifact@main
      with:
       name: create_llvm_prof-zip
       path: |
         *.zip

  publish-release:
    needs: [build_release]
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Restoring artifacts
      uses: actions/download-artifact@main
      with:
        path: ${{ github.workspace }}
    - name: Release Tag
      id: release_tag
      run: echo "TAG_NAME=$(date -u +%d%m%Y%I%M)" >> $GITHUB_ENV
    - name: Create Release
      run: gh release create ${{ env.TAG_NAME }} --generate-notes -p */*.zip
    - name: Release Check
      run: gh release list -L 1 > list
    - name: Prepare release message
      run: gh release view $(cat list | awk '{ print substr( $0, 1, length($0)-45 ) }') > release-text
